#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os, sys
from kconfiglib import Kconfig # type: ignore
from menuconfig import menuconfig

def mconf_set_env():
    """
    Set Kconfig Env
    """
    os.environ["MENUCONFIG_STYLE"] = "default selection=fg:white,bg:blue"
    os.environ["KCONFIG_CONFIG"] = os.path.join(".my_config")
    os.environ["KCONFIG_CONFIG_HEADER"] = "# Generated by My Kconfig Demo"
    os.environ["KCONFIG_AUTOHEADER"] = os.path.join("my_config.h")
    os.environ["CONFIG_"] = ""

def mconfig(argv):
    mconf_set_env()
    kconf = Kconfig(filename="./kconfig")   #加载kconfig文件
    menuconfig(kconf)

    kconf.write_config("./main/my_config/.my_config") #
    kconf.write_autoconf("./main/my_config/my_config.h")

if __name__ == "__main__":
    mconfig(sys.argv)
